permalink: /:year-:month-:day/:title.html
# github setting
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# Site settings
title: "blogs"
description: "Do not go gentle into that good night..."
baseurl: ""
url: "http://omnbmh.github.io"
theme:
  site_name: Tech Blogs
  homepage_featured: 1
  homepage_posts: 2
  featured_wordcount: 20

# 下面的部分不能修改
#lsi: false
#safe: true
# source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#  kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
